apiVersion: networking.k8s.io/v1
#apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apps-ingress
  namespace: default
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: error
      port:
        name: svc-port
  rules:
    - host: apple.cluster-alpha.app.block51.net
      http:
        paths:
          - path: /first
            pathType: Prefix
            backend:
              service:
                name: apple-service
                port:
                  number: 5678
                  #name: svc-port
    - host: banana.cluster-alpha.app.block51.net
      http:
        paths:
          - path: /second
            pathType: Prefix
            backend:
              service:
                name: banana-service
                port:
                  number: 5678
                #  name: svc-port
